language: go
services:
  - docker

go:
  - "1.8"

script:
  - docker run --entrypoint=/go/src/github.com/Pixboost/transformimgs/test.sh -v $(pwd):/go/src/github.com/Pixboost/transformimgs  transformimgs

before_install:
  - docker build -t transformimgs -f Dockerfile.dev .
