language: go
services:
  - docker

go:
  - "1.8"

script:
  - docker run transformimgs /bin/sh -c "go test $(go list ./... | grep -v /vendor/)"

before_install:
  - docker build -t transformimgs -f Dockerfile.dev .
