version: '2'
services:
  transformimgs:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/usr/local/go/src/github.com/dooman87/transformimgs
    ports:
      - "8080:8080"