version: '2'
services:
  transformimgs:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/go/src/github.com/Pixboost/transformimgs
    ports:
      - "8080:8080"