FROM golang:1.9-alpine3.7

#Installing imagemagick
RUN apk add --no-cache imagemagick git

#Installing godeps
RUN go get github.com/golang/dep/cmd/dep

VOLUME /go/src/github.com/Pixboost/transformimgs/
WORKDIR /go/src/github.com/Pixboost/transformimgs/
ENTRYPOINT ["sh", "/go/src/github.com/Pixboost/transformimgs/run.sh"]
