version: '2'
services:
  transformimgs:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/go/src/github.com/Pixboost/transformimgs
    ports:
      - "8080:8080"
  nginx:
    image: nginx:1.13.1-alpine
    volumes:
      - ./img/processor/test_files:/usr/share/nginx/html:ro
    ports:
      - "9090:80"
