FROM golang:1.8-alpine

#Installing imagemagick
RUN apk add --no-cache imagemagick git

#Installing godeps
RUN go get github.com/golang/dep/cmd/dep

VOLUME /usr/local/go/src/github.com/Pixboost/transformimgs/
WORKDIR /usr/local/go/src/github.com/Pixboost/transformimgs/
ENTRYPOINT ["sh", "/usr/local/go/src/github.com/Pixboost/transformimgs/run.sh"]
